# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\GitHub\DigitalOrder\main page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 624)
        MainWindow.setMinimumSize(QtCore.QSize(1120, 624))
        MainWindow.setMaximumSize(QtCore.QSize(1120, 624))
        MainWindow.setStyleSheet("background-color: rgb(9, 11, 11);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(572, 108, 10, 408))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\GitHub\\DigitalOrder\\main page components/Line 1.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(14, 21, 1012, 60))
        self.label_2.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(26, 28, 26);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 230, 141, 141))
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 193, 312, 239))
        self.label_3.setStyleSheet("image: url(:/main page/Iniciar Caixa text.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\GitHub\\DigitalOrder\\main page components/Iniciar Caixa text.png"))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(15, 17, 71, 67))
        font = QtGui.QFont()
        font.setFamily("MADE TOMMY")
        font.setPointSize(40)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"color: rgb(250, 247, 247);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(976, 34, 34, 34))
        self.label_4.setStyleSheet("image: url(:/main page/greem light notification.png);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\GitHub\\DigitalOrder\\main page components/greem light notification.png"))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1036, 21, 60, 60))
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(993, 537, 95, 61))
        self.label_5.setStyleSheet("image: url(:/main page/logo text.png);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\GitHub\\DigitalOrder\\main page components/logo text.png"))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(83, 20, 880, 61))
        font = QtGui.QFont()
        font.setFamily("MADE TOMMY")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"font: 30pt \"MADE TOMMY\";\n"
"alternate-background-color: rgba(255, 255, 255,0);\n"
"gridline-color: rgba(255, 255, 255,0);\n"
"selection-color: rgba(255, 255, 255,0);\n"
"border-color: rgba(255, 255, 255,0);\n"
"color: rgb(250, 247, 247);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(384, 237, 141, 141))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\GitHub\\DigitalOrder\\main page components/start caixa botom.png"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1036, 21, 60, 60))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\GitHub\\DigitalOrder\\main page components/menu botom.png"))
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.pushButton_2.raise_()
        self.label_4.raise_()
        self.pushButton_3.raise_()
        self.label_5.raise_()
        self.lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/main page/start caixa botom.png\"/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "d."))
import components_rc
