# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\GitHub\DigitalOrder\pagina de caixa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 624)
        MainWindow.setMinimumSize(QtCore.QSize(1120, 624))
        MainWindow.setMaximumSize(QtCore.QSize(1120, 624))
        MainWindow.setStyleSheet("background-color: rgb(9, 11, 9);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(14, 21, 1012, 60))
        self.label_6.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(26, 28, 26);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(83, 20, 880, 61))
        font = QtGui.QFont()
        font.setFamily("MADE TOMMY")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setMouseTracking(True)
        self.lineEdit_2.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"font: 30pt \"MADE TOMMY\";\n"
"alternate-background-color: rgba(255, 255, 255,0);\n"
"gridline-color: rgba(255, 255, 255,0);\n"
"selection-color: rgba(255, 255, 255,0);\n"
"border-color: rgba(255, 255, 255,0);\n"
"color: rgb(250, 247, 247);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(15, 17, 71, 67))
        font = QtGui.QFont()
        font.setFamily("MADE TOMMY")
        font.setPointSize(40)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"color: rgb(250, 247, 247);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(976, 34, 34, 34))
        self.label.setStyleSheet("image: url(:/main page/greem light notification.png);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1036, 21, 60, 60))
        self.pushButton_3.setStyleSheet("image: url(:/main page/menu botom.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.table = QtWidgets.QFrame(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(19, 126, 428, 174))
        self.table.setStyleSheet("background-color: rgb(26, 28, 26);\n"
"border-radius:7px;")
        self.table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table.setObjectName("table")
        self.table_icons = QtWidgets.QFrame(self.table)
        self.table_icons.setGeometry(QtCore.QRect(100, 12, 310, 114))
        self.table_icons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_icons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_icons.setObjectName("table_icons")
        self.pushButton = QtWidgets.QPushButton(self.table_icons)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 35, 34))
        self.pushButton.setStyleSheet("image: url(:/main page/1.png);\n"
"background-color: rgb(9, 11, 9);\n"
"border-radius:5px;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.caixa = QtWidgets.QFrame(self.centralwidget)
        self.caixa.setGeometry(QtCore.QRect(464, 126, 637, 474))
        self.caixa.setStyleSheet("background-color: rgb(26, 28, 28);\n"
"border-radius:7px;\n"
"")
        self.caixa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa.setObjectName("caixa")
        self.delivery = QtWidgets.QFrame(self.centralwidget)
        self.delivery.setGeometry(QtCore.QRect(19, 333, 170, 278))
        self.delivery.setStyleSheet("background-color: rgb(26, 28, 26);\n"
"border-radius:5px;\n"
"")
        self.delivery.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.delivery.setFrameShadow(QtWidgets.QFrame.Raised)
        self.delivery.setObjectName("delivery")
        self.label_3 = QtWidgets.QLabel(self.delivery)
        self.label_3.setGeometry(QtCore.QRect(1, 5, 90, 21))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"image: url(:/main page/delivery.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.statistics = QtWidgets.QFrame(self.centralwidget)
        self.statistics.setGeometry(QtCore.QRect(205, 316, 243, 295))
        self.statistics.setStyleSheet("background-color: rgb(26, 28, 26);\n"
"border-radius:7px;")
        self.statistics.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statistics.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statistics.setObjectName("statistics")
        self.label_4 = QtWidgets.QLabel(self.statistics)
        self.label_4.setGeometry(QtCore.QRect(76, 1, 92, 35))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"image: url(:/main page/statistics.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(29, 100, 66, 21))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"image: url(:/main page/tables.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(472, 100, 57, 20))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"image: url(:/main page/order.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "d."))
import main page componets_rc
